# Generated by Django 6.0.7 on 2026-08-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=100)),
                ('report_type', models.CharField(max_length=100)),
                ('generated_by', models.CharField(max_length=100)),
                ('generated_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
