# Generated by Django 6.0.7 on 2026-08-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_appointment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
