# Generated by Django 6.0.7 on 2026-08-15 12:54

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_admission_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admission_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='bed_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='admission',
            name='diagnosis',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='admission',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='admission',
            name='patient',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
