# Generated by Django 6.0.7 on 2026-08-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_admission_admission_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admission_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='patient',
            field=models.CharField(max_length=50),
        ),
    ]
