# Generated by Django 6.0.7 on 2026-09-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_alter_admission_admission_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='id',
            new_name='admission_id',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='ward',
        ),
        migrations.AddField(
            model_name='admission',
            name='admission_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='admission',
            name='doctor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='room_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='admission',
            name='admission_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='bed_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='admission',
            name='patient',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(default='Admitted', max_length=50),
        ),
    ]
