# Generated by Django 6.1.1 on 2026-09-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='keywords',
            field=models.TextField(blank=True, help_text='Enter related symptoms or diseases separated by commas'),
        ),
    ]
