# Generated by Django 6.0.7 on 2026-09-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
