# Generated by Django 6.0.7 on 2026-09-10 07:09

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_alter_labtest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='labtest',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='labtest',
            name='doctor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='labtest',
            name='technician',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='result',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
