# Generated by Django 6.0.7 on 2026-08-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
