# Generated by Django 6.0.7 on 2026-09-11 07:00

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Receptionist', 'Receptionist'), ('Pharmacist', 'Pharmacist'), ('Lab Technician', 'Lab Technician'), ('Administrator', 'Administrator'), ('Accountant', 'Accountant'), ('Ward Assistant', 'Ward Assistant'), ('Technician', 'Technician')], max_length=30),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
