# Generated by Django 6.0.7 on 2026-08-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=50)),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
