# Generated by Django 6.0.7 on 2026-09-09 15:02

import django_mongodb_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_medicine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
    ]
